### ISSUE TITLE
can't easily find configuration for, say, http check

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#57] opened 2015-04-29 22:17 UTC
i have only 1 endpoint and i want to modify the http check config
i have to go to endpoints, select my endpoint and then go to configuration
this is confusing to me because when i think "i want to change my http check config" i really don't think about going to endpoints, especially since I'm a customer who only monitors one site so i don't even think of the concept of endpoints anymore. note that #55 might alleviate this but i wonder if we can perhaps have a side entry "checks" from which i can easily go to my http check config

**Comment by nopzor1200** [comment] 2015-04-29 23:54
I agree with #55 but I'm not sure where else we would provide access to the check configuration from.

**Comment by woodsaj** [comment] 2015-04-30 10:18
The fact that you are thinking in terms of checks is the real issue.  The user should only be thinking in terms of endpoints.

If you are a user with 1 website, then you create 1 endpoint.  If you want to change how that endpoint is being monitored, then it seems fairly clear to me, but i a biased, that you would navigate to the endpoint configuration page.

From the UI perspective, users can only ever create/edit endpoints as a whole.  ie, there is only one page where configuration can be modified and that is the endpoint configuration page. Users never create individual checks, they only create endpoints and configure how these endpoints should be monitored.

We definitely need to refine the endpoint configuration page so that it is more like the "new endpoint" modal.  Perhaps this will help with the user experience.

**Comment by nopzor1200** [comment] 2015-05-07 14:16
100% agreed that dashboards need to be better connected or related to the endpoints, and endpoint status, and endpoint configuration, etc etc.

**Comment by nopzor1200** [comment] 2015-05-07 14:17
Personally I'd really like to show the endpoint health somewhere within the endpoint dashboards

**Comment by bulletfactory** [comment] 2015-05-18 21:49
After discussion:

- we dont think the problem is related to 1 versus many endpoints
- related to issue #55 
- there needs to be some better linkage between a grafana dashboard about an endpoint and litmuis-speciifc stuff about an endpoint.

**Comment by mattttt** [comment] 2015-05-18 21:50
Need to include in endpoint dashboards (in some way, place):
- Current State of Endpoint
- Uptime of endpoint (health over time)

**Comment by nopzor1200** [comment] 2015-06-23 16:43
We do now show uptime % of endpoint

We are looking at the possibility of adding singlestat panel for "last" health. In most use cases "last" health will be synomymous with "current" health (as shown in endpoint.list)

**Comment by nopzor1200** [comment] 2015-07-11 00:44
Closing this out. We now show endpoint health in the dashboard. #55 is still valid.

**Comment by Dieterbe** [comment] 2015-07-11 04:10
> Closing this out. We now show endpoint health in the dashboard. #55 is still valid.

that's not what this is about? I thought we agreed there should be a way to go from say, a http dashboard to the http configuration. AFAIK we still don't have this. you say 55 is still valid but it's been closed for more than a month. am i missing something?

**Comment by mattttt** [comment] 2015-11-06 23:25
This is still an issue, and will hit a head by moving all Litmus functionality to panels. Closing this ticket to be addressed in future designs.

**Comment by Dieterbe** [comment] 2015-11-14 23:58
@mattttt i don't understand why to close the ticket if we agree there's an issue and it should and will be fixed. the benefit of keeping it open until it's fixed is so we can guarantee it's addressed at some point, by closing it early we may forget about it and also give the impression it's no longer an issue.
if your intent is to consolidate various design issues into one and that's why you rather close this, then IMHO you should link to another issue where this issue is specifically mentioned

**Comment by Dieterbe** [comment] 2015-11-14 23:58
if there's a larger workflow issue that i'm not seeing, let's talk!

**Comment by woodsaj** [comment] 2016-04-04 12:56
Worldping dashboards now have a an "Endpoint Nav" panel that allows you to navigate directly from dashboards to configuration pages.

![image](https://cloud.githubusercontent.com/assets/8415072/14248534/a1b35c60-faa7-11e5-8548-b52d09d0c0d8.png)

**Closed by woodsaj** 2016-04-04 12:56 UTC
Labels: enhancement, frontend, litmus
