### ISSUE TITLE
event panel tweaks

### ISSUE THREAD

**Issue by nopzor1200** [raintank/grafana#167] opened 2015-06-04 07:16 UTC
A sample event dashboard is all set up with appropriate template variables for endpoint,collector,protocol,severity. It is working great as long as only one variable from each pulldown is selected. It's called "eventtest"

I think it's looking good, just needs two changes:

1. Ability to accept graphite-style globs via grafana multiselect variables.
2. Initial styling

References raintank/grafana#44

**Comment by mattttt** [comment] 2015-06-05 00:45
Styling happening in branch: mattttt_event_panel

- Talked to Torkel today and confirmed that mediaqueries is probably the best way to go to handle the responsive panel layout. Tables for the wide layouts and flexbox for the small ones. 
- The mediaqueries are pretty straightforward, but need to do some research on how to use CSS tables in lieu of html tables.

**Comment by mattttt** [comment] 2015-06-05 16:52
Pull request https://github.com/raintank/grafana/pull/174 submitted for updated icon styles, but it's held up with a conflict that Im unsure how to determine.

**Comment by woodsaj** [comment] 2015-06-09 06:03
@mattttt if you cant merge a branch due to conflicts, you just need to merge master into your branch. When you do this, git will tell you which files are conflicting and you can manually resolve them.  After the merge is committed and pushed to the origin, you will be able to merge your PR.

```
# checkout master
git checkout master
# ensure master is up to date
git pull
# checkout our your branch
git checkout mattttt_event_panel
# ensure your branch is up to date.
git pull
# merge master with your branch
git merge master
# show the merge status. git will tell you which files have conflicts
git status 
# fix the conflicts
# git add <conflicted files>
# commit the merge
git commit
# push the merge to github 
git push origin mattttt_event_panel
```
If you then go to your pull request in GitHub, you will now be able to merge it.

**Closed** 2015-06-10 12:09 UTC
Labels: litmus
