### ISSUE TITLE
failure to update monitor state in database can lead to bogus notifications

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#323] opened 2015-07-13 16:12 UTC
currently the alerting executor, if it can't update the monitor state, not much special happens
https://github.com/raintank/grafana/blob/master/pkg/alerting/executor.go#L113

the problem is that subsequent runs of the job send a notification when current state != state in db.
if we are having trouble updating the state in the db, it is likely that this inequality holds true a lot more often and we send duplicate notifications.  this is probably a cause of #280

**Comment by woodsaj** [comment] 2015-07-13 17:06
perhaps we have return an error if no rows are updated.

https://github.com/raintank/grafana/blob/master/pkg/services/sqlstore/monitor.go#L862

```
res, err := sess.Exec(rawSql, cmd.State, cmd.Updated, cmd.Id, cmd.State)
if err != nil {
    return err
}
if res.RowsAffected() < 1 {
  return errors.New("Row not updated")
}
```

**Comment by Dieterbe** [comment] 2015-07-13 17:10
the problem is *future* alerting runs behave errorously when the table hasn't been updated.
so we can either only allow a state change (and notification) if we can guarantee the last known state is accurate (which requires updating the timestamp at every run). also requires some more thinking around out-of-order finishing of jobs.

we can also leverage RAM and store the last known states in RAM (still keeping state in db, but now it's less critical, though we can still run into this problem if the worker crashes)

**Comment by woodsaj** [comment] 2015-07-13 17:15
would just adding a `AND state_change < ?` condition fix this.  So that we only update the row if our update timestamp is greater then the last update committed to the DB.

**Comment by Dieterbe** [comment] 2015-07-13 17:16
no. the problem is that the last known state can be out of date (e.g. it could be normal, because a previous job tried to update it to critical, but the update failed), and if our state is critical again, we send a notification twice.

**Comment by woodsaj** [comment] 2015-07-13 17:32
the updateMonitorStateCmd is how we persist the current state of a check.   If that fails then we should just consider the entire job as failed and not send any notifications.

The state change failing to commit is an exception, not an expected behavior. 

so if we change the SQL statement to 
```
UPDATE monitor SET state=?, state_change=? WHERE id=? AND state_change < ?
```

and also have the UpdateMonitorState function return an error if no rows are updated.  Then we can have the notifications only sent if https://github.com/raintank/grafana/blob/master/pkg/alerting/executor.go#L113 doesnt return an error.

**Comment by Dieterbe** [comment] 2015-07-14 19:22
ah yes, i see what you're saying now. that sounds good. i'll give this a shot.

**Comment by woodsaj** [comment] 2015-07-15 12:39
one thing to note is that if the udateMonitorStateCmd fails because the state_change time in the DB is more recent then the timestamp we are trying to set, then we need to stop execution and return a 'fatal' error so that the job is not re-queued.

**Comment by Dieterbe** [comment] 2015-07-15 12:46
right.

**Closed** 2015-07-21 15:10 UTC
