### ISSUE TITLE
socketio api should drop bad metrics

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#406] opened 2015-08-11 14:34 UTC
such as when `b.OrgId == 0`
and inc a statsd counter.

probably a lot more validation needs to happen.

let's do this *after* we merge the nsq related refactorings.

**Comment by woodsaj** [comment] 2016-04-04 11:55
this is a dupe of https://github.com/raintank/grafana/issues/568

**Closed by woodsaj** 2016-04-04 11:55 UTC
