### ISSUE TITLE
mixed up endpoints ?

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#380] opened 2015-07-29 15:50 UTC
in dev i have 2 endpoints:
* `metrics20.org` which has an http check on metrics20.org:8888/bad/80 which should be failing constantly
* `metrics20 daily 5min 50 dev` which has an http check on metrics20.org:8888/custom/daily-5min-50-dev which is up all day except a 5min period each 24 hours. in this case i accidentally broke the monitoring config (see #379) so my endpoint was down briefly:
![temp-broken](https://cloud.githubusercontent.com/assets/20774/8962286/15fc82ac-361a-11e5-80f6-fc5955b90465.png)

the interesting part is the first endpoint though.
![familiar](https://cloud.githubusercontent.com/assets/20774/8962318/3ad5122e-361a-11e5-98fa-d76ab0c0f040.png)

I think litmus is getting the configs confused. the first endpoint should be failing a lot more (80% of the requests get a broken response)

**Comment by Dieterbe** [comment] 2015-07-29 15:53
also the fact i can arbitrarily go back in time, there's a long data history even though i only added it around 17:40 CEST today.

if it helps (or maybe i'm just trying to confuse you) the 2nd endpoint (`metrics20 daily 5min 50 dev`) used to be called `metrics20.org`)

**Comment by nopzor1200** [comment] 2015-07-29 16:03
I think its just a dashboard query error on the DNS summary panel looks like

**Comment by Dieterbe** [comment] 2015-07-29 19:48
so i changed the name of `metrics20.org` to `metrics20.org /bad/80`, after which, when i load the dashboard again, i get the correct timerange (populated as of 17:40, and mostly red)
so i guess changing the endpoint name to something more unique makes me able to access the true data again.

**Comment by woodsaj** [comment] 2015-07-30 02:32
i am fairly sure this is an issue with the data in elasticsearch.

@Dieterbe can you explain in more detail what lead up to this.

1) you created an endpoint with the name "metrics20.org", lets call it endpoint1
2) you renamed endpoint1 to "metrics20 daily 5min 50 dev"?
3) you created a new endpoint with the name "metrics20.org", lets call it endpoint2?
4) when querying endpoint2 you get endpoint1's data?

**Comment by nopzor1200** [comment] 2015-07-30 03:39
We restarted a conversation around this today in NY.

So especially with the new "one step URL or domain or hostname or IP" input (which I really like), this whole concept of "input" -> "endpoint human name" -> "endpoint slug name"  needs to be revisited.

The thought is we might want to show/educate the slug as part of the add endpoint process.

@woodsaj My Q is: What is the level of pain in renaming "endpoint human name" and "endpoint slug name", once an endpoint has been created? Im guessing maybe there's pain with renaming the slug? Keep in mind none of our dashboards represent endpoint or collector slugs directly I guess.

Thoughts?

**Comment by Dieterbe** [comment] 2015-07-30 08:29
> @Dieterbe can you explain in more detail what lead up to this.

> 1) you created an endpoint with the name "metrics20.org", lets call it endpoint1
2) you renamed endpoint1 to "metrics20 daily 5min 50 dev"?
3) you created a new endpoint with the name "metrics20.org", lets call it endpoint2?
4) when querying endpoint2 you get endpoint1's data?

exactly. and then:
5)  i gave endpoint2 a unique name `metrics20.org /bad/80`
6) i was now getting the proper data in the dashboard for endpoint2.

**Comment by woodsaj** [comment] 2015-07-30 10:31
yep, this definitely sounds like the issue is with elasticsearch queries.
There is a known problem with deleting an endpoint or changing the endpoint.Name then creating a new endpoint with the firsts original name.  The cause of the problem is due to us using org_id.seriesName as the unique key of a metric definition, even though it is not unique (due to the above two cases).  When a metric arrives into raintank-metric it checks to see if it has seen the non-unique ID and if so just assumes that it is valid.

This should be fixed by: https://github.com/raintank/raintank-metric/issues/11

**Comment by woodsaj** [comment] 2015-11-04 10:15
This was actually fixed with:  https://github.com/raintank/graphite-kairosdb/commit/9abaacbad2ed311fbb34e18368fe7756eb83b18a

**Closed by woodsaj** 2015-11-04 10:15 UTC
