### ISSUE TITLE
endpoint display broken in current master

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#430] opened 2015-08-25 10:28 UTC
current master in dev stack, after adding an endpoint:
![endpoint-display](https://cloud.githubusercontent.com/assets/20774/9464506/c2df2ce4-4b24-11e5-88d0-b41dd460ce7a.png)
note the status panel obviously, but also the header/logo upper left side, the dashboard icon there is wrong too.

**Comment by Dieterbe** [comment] 2015-08-25 10:29
fwiw, no events/errors in js console, all http requests return in 200 or 304

**Comment by Dieterbe** [comment] 2015-08-25 10:32
the header is broken on every page.
![also-broken](https://cloud.githubusercontent.com/assets/20774/9464570/47440fe0-4b25-11e5-9f7f-43f60410e491.png)

**Comment by mattttt** [comment] 2015-11-06 23:39
Cannot reproduce across multiple browsers and havent gotten any other reports. Closing.

**Closed by mattttt** 2015-11-06 23:39 UTC
