### ISSUE TITLE
Litmus Events: Template Variable values not being populated

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#539] opened 2015-12-29 19:07 UTC
In the event dashboard (in production), the template variables are not being populated when `All` is selected:

![events-all-values](https://cloud.githubusercontent.com/assets/2886187/12040219/0fe2cdac-ae35-11e5-9e7c-2c0a97ef929a.gif)

**Comment by woodsaj** [comment] 2016-01-04 14:19
The problem is that "multi format" setting of the "endpoint" template variable is set to "regex values" as this is what is needed by "raintank events panel".  
So when "all" is selected the graphite query to get the list of probes uses "litmus.<regex values>.*" format, which is not a valid graphite query format and an empty set is returned.

This cant be resolved until https://github.com/grafana/grafana/issues/2918 is resolved.

**Comment by woodsaj** [comment] 2016-04-04 11:07
this was fixed in worldping-app

**Closed by woodsaj** 2016-04-04 11:07 UTC
Labels: bug
